name: Publish Website

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: npm ci

    - name: format
      run: npm run format

    - name: test
      run: npm run test

    - name: build
      run: npm run build

    #- name: FTP-Deploy-Action
    #  uses: SamKirkland/FTP-Deploy-Action@3.1.1
    #  with:
    #    ftp-server: ftp://sunfire.awh.jp/
    #    ftp-username: accessto
    #    ftp-password: ${{ secrets.FTP_PASSWORD }}
    #    local-dir: public
    #    git-ftp-args: --remote-root /
    #    args: --delete --parallel=20 -x media